routes.py
from flask import Blueprint, render_template, url_for, request, redirect, session

routes = Blueprint('routes', __name__, template_folder='templates')

@routes.route('/loginPage')
def loginPage():
    if session.get('email') == None:
        return render_template('loginPage.html')
    else:
        return redirect(url_for('routes.mainPage'))

@routes.route('/registerPage')
def registerPage():
    if session.get('email') == None:
        return render_template('registerPage.html')
    else:
        return redirect(url_for('routes.mainPage'))

@routes.route('/mainPage')
def mainPage():
    if session.get('email') != None:
        from models import getUser, getFriendsPropositions, getRequestsToShow
        user = getUser(session.get('email'))
        friendsPropositions = getFriendsPropositions(session.get('email'))
        friendsSentRequests = getRequestsToShow(session.get('email'), "sent")
        friendsPendingRequests = getRequestsToShow(session.get('email'), "pending")

        return render_template('mainPage.html', user = user, friends = user.friends, pending_friends_requests = friendsPendingRequests, sent_friends_requests = friendsSentRequests, friends_propositions = friendsPropositions)
    else:
        return redirect(url_for('routes.loginPage'))

def containsNumber(value):
    for character in value:
        if character.isdigit():
            return True
    return False

@routes.route('/registerUser', methods=['POST', 'GET'])
def registerUser():
    if session.get('email') == None:
        if request.method == 'POST':
            name = request.form['name']
            surname = request.form['surname']
            email = request.form['email']
            password = request.form['password']

            import re

            if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
                return render_template('registerPage.html', error="Given email doesnt contain required elements!")

            if (containsNumber(name) is True) or (containsNumber(surname) is True):
                return render_template('registerPage.html', error="Given name or surname has digits!")

            from models import registerNewUser
            if(registerNewUser(name,surname,email,password)):
               return redirect(url_for('routes.loginPage'))
            else:
                return render_template('registerPage.html', error="User with given email already exists!")
        else:
            return redirect(url_for('routes.registerPage'))
    else:
        return redirect(url_for('routes.mainPage'))

@routes.route('/checkCredentials', methods=['POST', 'GET'])
def checkCredentials():
    if session.get('email') == None:
        if request.method == 'POST':
            email = request.form['email']
            password = request.form['password']

            import re

            if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
                return redirect(url_for('routes.loginPage'))
            else:
                from models import checkCredentials
                if(checkCredentials(email, password)):
                    session['email'] = email
                    return redirect(url_for('routes.mainPage'))
                else:
                    return redirect(url_for('routes.loginPage'))
        else:
            return redirect(url_for('routes.loginPage'))
    else:
        return redirect(url_for('routes.mainPage'))

@routes.route('/logout')
def logout():
    session.pop('email', None)
    return redirect(url_for('routes.loginPage'))

@routes.route('/addPost', methods=['POST', 'GET'])
def addPost():
    if session.get('email') != None:
        if request.method == 'POST':
            content = request.form['content']

            from models import addPost
            addPost(session.get('email'), content)
            return redirect(url_for('routes.mainPage'))
        else:
            return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.loginPage'))

@routes.route('/deletePost/<id>', methods=['GET'])
def deletePost(id):
    if session.get('email') != None:
        from models import deletePost
        deletePost(id)
        return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.mainPage'))

@routes.route('/sendFriendsRequest/<id>', methods=['GET'])
def sendFriendsRequest(id):
    if session.get('email') != None:
        from models import friendsRequestOperations
        friendsRequestOperations(session.get('email'), id, 'send')
        return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.loginPage'))

@routes.route('/acceptFriendsRequest/<id>', methods=['GET'])
def acceptFriendsRequest(id):
    if session.get('email') != None:
        from models import friendsRequestOperations
        try:
            if friendsRequestOperations(session.get('email'), id, 'accept'):
                addFriend(session.get('email'), id)
                return redirect(url_for('routes.mainPage'))
        except TypeError:
            return redirect(url_for('routes.mainPage'))
        else:
            return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.mainPage'))


@routes.route('/declineFriendsRequest/<id>', methods=['GET'])
def declineFriendsRequest(id):
    if session.get('email') != None:
        from models import friendsRequestOperations
        if friendsRequestOperations(session.get('email'), id, 'decline'):
            return redirect(url_for('routes.mainPage'))
        else:
            return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.loginPage'))

@routes.route('/addFriend/<id>', methods=['GET'])
def addFriend(id):
    if session.get('email') != None:
        if request.method == 'GET':
            from models import addFriend
            addFriend(session.get('email'), id)
            return redirect(url_for('routes.mainPage'))
        else:
            return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.loginPage'))

@routes.route('/deleteFriend/<id>', methods=['GET'])
def deleteFriend(id):
    if session.get('email') != None:
        if request.method == 'GET':
            from models import deleteFriend
            deleteFriend(session.get('email'), id)
            return redirect(url_for('routes.mainPage'))
        else:
            return redirect(url_for('routes.mainPage'))
    else:
        return redirect(url_for('routes.loginPage'))

templates/loginPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login view</title>
</head>
<body>
 <form action = "http://localhost:5000/checkCredentials" method = "POST">
         <p>Email <input type = "text" name = "email" /></p>
         <p>Password <input type = "password" name = "password" /></p>
        <p><a href="{{ url_for('routes.registerPage') }}">Go to register page!</a></p>
         <p><input type = "submit" value = "submit" /></p>
      </form>
</body>
</html>

templates/mainPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main view</title>
</head>
<body>
<div style="float: left">
<h3>Flask-socialapp</h3>
<form action = "http://localhost:5000/addPost" method = "POST">
         <p>Post content: <input type = "text" name = "content" style="width: 200px; height: 100px;"/></p>
         <p><input type = "submit" value = "submit" /></p>
         </form>
</br>
    <h3>Your pending friends requests:</h3>
    {% for pending_friend_request in pending_friends_requests %}
    {{pending_friend_request.name}} {{pending_friend_request.surname}} </br>
    Pending..  <a href="{{ url_for('routes.declineFriendsRequest', id = pending_friend_request.id) }}">Cancel</a>
    </br> </br>
    {% endfor %}

    <h3>Friends requests from other users:</h3>
    {% for sent_friend_request in sent_friends_requests %}
    {{sent_friend_request.name}} {{sent_friend_request.surname}} </br>
    <a href="{{ url_for('routes.acceptFriendsRequest', id = sent_friend_request.id) }}">Accept</a>
    <a href="{{ url_for('routes.declineFriendsRequest', id = sent_friend_request.id) }}"> Decline</a>
    </br> </br>
    {% endfor %}

    <h3>Your friends:</h3>
    {% for friend in friends %}
    {{friend.name}} {{friend.surname}} </br>
    <a href="{{ url_for('routes.deleteFriend', id = friend.id) }}">Delete</a>
    </br>
    {% endfor %}

    <h3>Friends propositions:</h3>
    {% for friend_proposition in friends_propositions %}
    {{friend_proposition.name}} {{friend_proposition.surname}} </br>
    <a href="{{ url_for('routes.sendFriendsRequest', id = friend_proposition.id) }}">Send a request</a>
    </br> </br>
    {% endfor %}

    <h3><a href="{{ url_for('routes.logout') }}">Logout!</a></h3>
    </div>
    <div style="float:left; margin-left: 100px;">
    <h2>Posts</h2>
        {% for friend in friends %}
        {% for i in range(friend.posts.count()) %}
        <h4> {{ friend.name }} {{friend.surname}} </h4>
        {{ friend.posts[i].created_at }} </br>
        {{ friend.posts[i].content }}
        {% endfor %}
        {% endfor %}
    </div>
    <div style="float:left; margin-left: 100px;">
    <h2>Your posts</h2>
        {% for i in range(user.posts.count()) %}
        <h4>You</h4>
        {{ user.posts[i].created_at }} </br>
        {{ user.posts[i].content }}
        </br>
        <a href="{{ url_for('routes.deletePost', id = user.posts[i].id) }}">Delete post</a>
        {% endfor %}
    </div>


</form>
</body>
</html>

templates/registerPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register view</title>
</head>
<body>
 <form action = "http://localhost:5000/registerUser" method = "POST">
         <p>Name <input type = "text" name = "name" /></p>
         <p>Surname <input type = "text" name = "surname"/></p>
         <p>E-mail <input type = "text" name = "email" /></p>
         <p>Password <input type = "password" name = "password" /></p>
         <p><a href="{{ url_for('routes.loginPage') }}">Return to login page!</a></p>
         <h3>{{error}}</h3>
         <p><input type = "submit" value = "submit" /></p>
      </form>
</body>
</html>